### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by tjhunkin** [dracula/adminer#2]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by douglasdamasio** [comment]
Hey @tjhunkin again!!
This project is not dead!! According with explanation of this [issue](https://github.com/dracula/adminer/issues/1), the project is waiting for the official version of Dracula UI.
I'm closing this issue, for new bug or problem open the new issue, please. Thanks again man and thanks for the tip

**Comment by wildone** [comment]
looks dead...
